from typing import Protocol, Iterable, Optional, Dict, Any
import sqlite3


class DatabasePort(Protocol):
    def connect(self) -> sqlite3.Connection: ...


class UserRepositoryPort(Protocol):
    def find_by_username(self, username: str) -> Optional[Dict[str, Any]]: ...

    def create(self, username: str, password_hash: str, role: str) -> None: ...

    def promote_or_upsert_admin(self, username: str, password_hash: str) -> None: ...

    def list_all(self) -> Iterable[Dict[str, Any]]: ...


class BookRepositoryPort(Protocol):
    def list_all(self) -> Iterable[Dict[str, Any]]: ...

    def list_available(self) -> Iterable[Dict[str, Any]]: ...

    def search(self, q: str) -> Iterable[Dict[str, Any]]: ...

    def add(self, title: str, author: str, year: int, copies: int) -> None: ...

    def get_by_id(self, book_id: int) -> Optional[Dict[str, Any]]: ...

    def decrease_stock(self, book_id: int) -> None: ...

    def increase_stock(self, book_id: int) -> None: ...

    def update_stock(self, book_id: int, new_total: int) -> None: ...

    def delete(self, book_id: int) -> None: ...


class LoanRepositoryPort(Protocol):
    def create(self, data: Dict[str, Any]) -> None: ...

    def find_active_by_user_and_book(self, user_id: int, book_id: int) -> bool: ...

    def find_active_by_id_and_user(self, loan_id: int, user_id: int) -> Optional[Dict[str, Any]]: ...

    def mark_returned(self, loan_id: int) -> None: ...

    def active_loans_by_user(self, user_id: int) -> Iterable[Dict[str, Any]]: ...

    def history_by_user(self, user_id: int) -> Iterable[Dict[str, Any]]: ...

    def create_loan_and_decrease_stock(self, data: Dict[str, Any]) -> None: ...
